name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build

      - name: Test
        run: |
          cargo test

      - name: Format Check
        run: |
          cargo fmt
          git diff --quiet HEAD
 
        
