name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install SDL2
        run: |
          sudo apt install -y libsdl2-dev

      - name: Build
        run: |
          cargo build

      - name: Format Check
        run: |
          cargo fmt
          git diff --quiet HEAD
 
        
